server:
  address: 127.0.0.1
  port: 8080
spring:
  datasource:
    druid:
      username: admin
      password: 123
    vbankds:
      name: vbankds
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/testlink?useUnicode=true&characterEncoding=utf-8&&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
      username: qa_rw
      password: 123


#LOG
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.rrx.vbank: debug
  config: classpath:log4j2-win-dev.yml